- hosts: sysadmin
  become: yes
  become_user: root

  vars_files:
    - vars.yml

  roles:
#    - { role: etais, tags: etais }
#    - { role: dns, tags: dns }
#    - { role: apache, tags: apache }
#    - { role: email, tags: email }
#    - { role: tls, tags: tls }
    - { role: filesystem, tags: filesystem }
#    - { role: container, tags: container }
#    - { role: devops, tags: devops }
#    - { role: kubernetes, tags: kubernetes }
