---
- name: restart nfs-server
  service:
    name: nfs-server
    state: restarted
    enabled: yes
    masked: no
  listen: restart nfs-server

- name: restart firewalld
  service:
    name: firewalld
    state: restarted
    enabled: yes
    masked: no
  listen: restart firewalld

- name: restart smb
  service:
    name: smb
    state: restarted
    enabled: yes
    masked: no
  listen: restart smb