- name: open ports 50080 and 58080
  firewalld:
    permanent: yes
    state: enabled
    port: "{{ item }}/tcp"
  with_items:
    - "50080"
    - "58080"
  notify: restart firewalld

- name: create traefik folder
  file:
    path: /etc/traefik
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Set traefik.toml file
  copy:
    src: traefik.toml
    dest: /etc/traefik/traefik.toml
    mode: 0755
    owner: root
    group: root

- name: docker run -d -p 50080:80 -p 58080:8080 -v /var/run/docker.sock:/var/run/docker.sock:ro -v /etc/traefik/traefik.toml:/traefik.toml:ro --restart=always traefik:v2.1.8
  docker_container:
    name: traefik
    image: traefik:v2.1.8
    ports:
      - "50080:80"
      - "58080:8080"
    mounts:
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind
        read_only: yes
      - source: /etc/traefik/traefik.toml
        target: /traefik.toml
        type: bind
        read_only: yes
    restart_policy: always
    pull: yes

- name: docker run -d --name whoami-traefik --label traefik.enable=true --label 'traefik.http.routers.router.rule=Host(`{{hostname}}.sa.cs.ut.ee`)' --label 'traefik.http.routers.router.entrypoints=web' registry.hpc.ut.ee/mirror/containous/whoami
  docker_container:
    name: whoami-traefik
    image: registry.hpc.ut.ee/mirror/containous/whoami
    labels:
      traefik.enable: "true"
      traefik.http.routers.router.rule: 'Host(`{{ hostname }}.{{ domain_name }}`)'
      traefik.http.routers.router.entrypoints: web
    restart_policy: always
    pull: yes 
    